Refactor auth, and rename to login
BarkApp/bark pull request #177
Opened 2023-01-25 23:13 UTC by haakonjacobsen

This PR simplifies the idToken verification by removing duplicated code between google and apple verification.

2023-01-26 11:38 UTC, AndreasWintherMoen requested changes
A few things here and there. See comments.

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +//TODO: fix type
Is this TODO for this PR or later? :D

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +    let payload: null | IAuthIDTokenPayload = null;
This could maybe be simplified with a ternary operator. Like this:

```
if (authProvider !== 'apple' && authProvider !== 'google') {
    return res.status(BAD_REQUEST).json({
        error: 'INVALID AUTH PROVIDER',
        message: `The authProvider ${authProvider} is not supported.`,
      });
}
const payload = (authProvider === 'apple') ? await verifyAppleJWT(idToken) : await verifyGoogleJWT(idToken);
```

Assuming you can await in a ternary operator... I haven't actually tested the code above :D

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +      // 498 is a custom error code for invalid token, not able to export this from http-status for some reason...
498 is not an _official_ HTTP status code. I guess an alternative would be 401, but I think this is okay...

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +      // eslint-disable-next-line no-magic-numbers
Instead of both of these comments you can just make 498 a variable...

```
const invalidTokenHttpStatusCode = 409;
```

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +    const userExists = await User.findOne({
You can use _User.exists_ if you don't actually need the returned user data.

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +    const emailExist = await User.findOne({ email: payload.email });
Same here. _User.exists_

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +    const emailExist = await User.findOne({ email: payload.email });
Also, to prevent these promises from running sequentially, check out [Promise.all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)

2023-01-26 11:38 UTC, AndreasWintherMoen commented on backend_rest/src/api/login.ts
> +      userId: userExists._id,
Hmmm, here you use the _userExists_ variable. Should probably be renamed to just _user_, and then you can disregard the comment above about the Mongoose _User.exists_ query.

2023-01-26 11:39 UTC, AndreasWintherMoen commented
Promise.all makes multiple awaits go fast!  ![bitmoji](https://sdk.bitmoji.com/render/panel/4fd49c6c-ce25-458f-9b32-eaea541f1922-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)

2023-01-26 16:17 UTC, haakonjacobsen commented on backend_rest/src/api/login.ts
> +      // 498 is a custom error code for invalid token, not able to export this from http-status for some reason...
I think it is🤔

https://http.dev/498

2023-01-26 16:28 UTC, haakonjacobsen commented on backend_rest/src/api/login.ts
> +//TODO: fix type
Later

2023-01-26 16:33 UTC, haakonjacobsen commented on backend_rest/src/api/login.ts
> +    let payload: null | IAuthIDTokenPayload = null;
Not sure about the await, but we might add more authentication providers later, so having a check for each seems more suitable in that situation.

2023-01-26 16:34 UTC, haakonjacobsen commented on backend_rest/src/api/login.ts
> +      // 498 is a custom error code for invalid token, not able to export this from http-status for some reason...
I'll change that so it follows the official status codes. Changing it to 401.

2023-01-26 17:57 UTC, haakonjacobsen commented on backend_rest/src/api/login.ts
> +    const emailExist = await User.findOne({ email: payload.email });
The Promise.all() is not that relevant here I think, as it is just two awaits, and it makes the code a bit messy🤠 

Cleaner code > minor performance boost.

2023-01-26 18:13 UTC, haakonjacobsen commented
All done🐶

2023-01-27 11:43 UTC, AndreasWintherMoen approved these changes

2023-01-27 12:01 UTC, merged