178 add viewed message endpoint
BarkApp/bark pull request #181
Opened 2023-01-26 19:20 UTC by haakonjacobsen

2023-01-27 23:06 UTC, AndreasWintherMoen requested changes

2023-01-27 23:06 UTC, AndreasWintherMoen commented on frontend/components/cards/ConversationCard.tsx
> +  const hasNewMessage = !conversation.messages[0].read.includes(userId);
I think this will crash if messages is an empty array. Should probably be:

```suggestion
  const hasNewMessage = !conversation.messages[0]?.read.includes(userId);
```

2023-01-27 23:07 UTC, AndreasWintherMoen commented
Just a small bug

2023-01-28 13:23 UTC, haakonjacobsen commented on frontend/components/cards/ConversationCard.tsx
> +  const hasNewMessage = !conversation.messages[0].read.includes(userId);
Nice spotted!
![bitmoji](https://sdk.bitmoji.com/render/panel/43533bc8-de9f-4e89-9f7d-f9a64b6254c4-eb1f676a-1fcc-49de-809c-bcc58ba85a75-v1.png?transparent=1&palette=1&width=246)

2023-01-28 15:06 UTC, AndreasWintherMoen approved these changes
👍

2023-01-28 15:18 UTC, merged