149 add favorite button for dogbreeds wiki
BarkApp/bark pull request #231
Opened 2023-02-20 21:27 UTC by haakonjacobsen

This PR adds a favorite button for all Breeds Screen if the user is logged in.

2023-02-20 21:36 UTC, AndreasWintherMoen requested changes
See comments.

2023-02-20 21:36 UTC, AndreasWintherMoen commented on frontend/components/buttons/HeaderButton.tsx
> +          ></PlaceholderMedia>
PlaceholderMedia can be self-enclosing

2023-02-20 21:36 UTC, AndreasWintherMoen commented on frontend/screens/profile/FavoritesScreen.tsx
> +          onRefresh={() => refetchTopBreeds()}
Can be simplified

```onRefresh={refetchTopBreeds}```

2023-02-20 21:36 UTC, AndreasWintherMoen commented on frontend/screens/profile/FavoritesScreen.tsx
> +              onPress={
Ugh, can't this one be simplified? I don't like ternary operators. What about something like

```
onPress={() => {
  if (!item) return;
  navigation.push('WikiScreen', { dogBreed: item });
}
```

2023-02-20 21:36 UTC, AndreasWintherMoen commented on frontend/screens/profile/FavoritesScreen.tsx
> +              onPress={
Or possibly 

```
onPress={item ?? () => {
  navigation.push('WikiScreen', { dogBreed: item });
}
```

This is a short-hand syntax of your code, just with nullish coalescing instead of ugly ternary operator.

2023-02-21 22:28 UTC, haakonjacobsen commented on frontend/screens/profile/FavoritesScreen.tsx
> +              onPress={
Did not work tho, using the first suggestion

2023-02-21 23:00 UTC, merged