Add DogSizeComparison
BarkApp/bark pull request #239
Opened 2023-03-11 17:47 UTC by haakonjacobsen

🚀

2023-03-11 19:00 UTC, AndreasWintherMoen reviewed
Some small stuff I'm not sure about. Otherwise neat 👌

2023-03-11 19:00 UTC, AndreasWintherMoen commented on frontend/components/elements/DogSizeComparison.tsx
> +  const shoulderCoordinate = svg.match(/cx="([^"]*)".*cy="([^"]*)"/);
Isn't it better to use an id in the svg? Something like `id=shoulderCoordinatePosition` on the circle (which could perhaps be a g instead?)

2023-03-11 19:00 UTC, AndreasWintherMoen commented on frontend/components/elements/DogSizeComparison.tsx
> +  const cxValue = Number(shoulderCoordinate[1]);
Do we need x value of shoulder coordinate? 🤔

2023-03-11 19:00 UTC, AndreasWintherMoen commented on frontend/components/elements/DogSizeComparison.tsx
> +  const min = useSharedValue(0);
Is 0 an appropriate min value?

2023-03-11 19:00 UTC, AndreasWintherMoen commented on frontend/components/elements/DogSizeComparison.tsx
> +  const [height, setHeight] = useState(175);
Initial value should be equal to progress defined above (or the other way around).

2023-03-14 23:20 UTC, haakonjacobsen commented on frontend/components/elements/DogSizeComparison.tsx
> +  const min = useSharedValue(0);
Yes, because the measure tape is going from 0 -> 220. However, we discussed this today and removed the possibility to set the height under 50cm.

2023-03-14 23:29 UTC, AndreasWintherMoen commented on frontend/components/elements/DogSizeComparison.tsx
> +  const min = useSharedValue(0);
Gotcha

2023-03-14 23:38 UTC, AndreasWintherMoen requested changes
Looks good but I have two questions. Otherwise it's fine even though the PR does a lot of stuff :D

2023-03-14 23:38 UTC, AndreasWintherMoen commented on frontend/utils/urlEncodeDogBreedName.ts
> +const urlEncodeDogBreedName = (breedName: string): string =>
Is this necessary? 😢 Can't `fetchSilhouetteSvg.ts` just take DogBreedName as parameter?

2023-03-14 23:38 UTC, AndreasWintherMoen commented on frontend/api/svg/fetchSilhouetteSvg.ts
> +    return fetchSilhouetteSvg('generic-dog', true);
Hmmmmm.... This won't actually work for silhouettes because we don't have a default silhouette, and I don't think we should have one because then we probably want to just not display the size comparison thing at all? 

Either 

```
export const fetchSilhouetteSvg = async (dogBreed: DogBreedName): Promise<string> => {
  const name = urlEncodeDogBreedName(dogBreed);
  const url = `${config.IMG_API_URI}silhouettes/${name}.svg`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error('Could not fetch SVG silhouette data for breed ' + dogBreed);
  }
  return response.text();
};
```

or add a fallback silhouette and replace `'generic-dog'` with that.

2023-03-16 08:47 UTC, haakonjacobsen commented on frontend/utils/urlEncodeDogBreedName.ts
> +const urlEncodeDogBreedName = (breedName: string): string =>
DogBreedName is wrong, it does not contain all DogBreedNames

2023-03-16 09:05 UTC, haakonjacobsen commented on frontend/utils/urlEncodeDogBreedName.ts
> +const urlEncodeDogBreedName = (breedName: string): string =>
I changed it back now

2023-03-16 09:05 UTC, haakonjacobsen commented on frontend/api/svg/fetchSilhouetteSvg.ts
> +    return fetchSilhouetteSvg('generic-dog', true);
Done🤠

2023-03-16 09:14 UTC, AndreasWintherMoen approved these changes
Woop woop

2023-03-16 09:21 UTC, merged